### ISSUE TITLE
How to run the example?

### ISSUE THREAD

**Issue by Shuang1997** [gtrll/orgpmp2#6]
I compiled successfully, but when I run the gpmp2_wam.py in examples, I get the error: ImportError: No module named orgpmp2.orgpmp2

**Comment by iskandersauma** [comment]
@HandsomeRocketboy Seems to me like it is a sourcing problem. For me, it works when I use
source ~/devel/setup.bash

**Comment by Shuang1997** [comment]
> @HandsomeRocketboy Seems to me like it is a sourcing problem. For me, it works when I use
> source ~/devel/setup.bash

thanks!
